In [2]:
Distance = [10,20,30,40]
Time = [2,3,4,5]
s = Distance/Time
s

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [17]:
import numpy as np


In [23]:
Distance = np.array([10,20,30,40])
Time = np.array([2,4,3,4])
s = Distance/Time
print(s)


[ 5.  5. 10. 10.]


In [24]:
type(s)

numpy.ndarray

In [27]:
l = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(l)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr[2][1] # INDEXING

8

In [32]:
arr.ndim #DIMENSION 

2

In [40]:
arr1 = np.array([[[[[1,2,3]]]]])
arr1.ndim

5

In [46]:
arr1 = np.array([[[[[1,2,3]]]]])
arr1.shape
arr1.size
arr1.ndim

5

In [43]:
arr.shape

(3, 3)

In [44]:
arr.size

9

In [47]:
arr.dtype

dtype('int32')

In [65]:
a = np.array([[2,2,4,4]])
b = np.array([[4,4,8,8]])
2*(a+b)

array([[12, 12, 24, 24]])