In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6,],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr [1][1] = 50 

In [10]:
arr

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [11]:
arr = np.array(arr,dtype = float)

In [12]:
arr

array([[ 1.,  2.,  3.],
       [ 4., 50.,  6.],
       [ 7.,  8.,  9.]])

In [13]:
arr = np.array([[23,43,56,61],[23,45,98,32]])

In [14]:
arr

array([[23, 43, 56, 61],
       [23, 45, 98, 32]])

In [19]:
passing_marks= 40
arr[arr>passing_marks]

array([43, 56, 61, 45, 98])

In [28]:
distance1 = np.array([12,16,22])
distance2 = np.array([10,12,15])
cycle = distance1 + distance2
cycle

array([22, 28, 37])

In [32]:
D = 30
cycle<D

array([ True,  True, False])

In [33]:
cycle[cycle<D]

array([22, 28])

In [52]:
s = np.array([['Delhi','Mumbai','Pune','Indore','Chennai'],['Delhi','MAha','Maha','MP','IN']])

In [56]:
s[:,3:]  #Row,Coloum

array([['Indore', 'Chennai'],
       ['MP', 'IN']], dtype='<U7')

In [58]:
s[:,3:][1][0]

'MP'

In [36]:
l1 = []
for i in s:
    for j in i:
        l1.append(j)
        
l1

['Delhi',
 'Mumbai',
 'Pune',
 'Indore',
 'Chennai',
 'Delhi',
 'MAha',
 'Maha',
 'MP',
 'IN']

In [4]:
a =np.array([[1,2,3],[4,5,6],[7,8,9,],[10,11,12]])
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [83]:
a1 = a[1:3,1:3]
a1[a1%3==0]


array([6, 9])

In [6]:
f6or i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
#a1.view()
#$a1.copy()