In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,77,8,9])

In [3]:
a

array([ 1,  2,  3,  4,  5,  6, 77,  8,  9])

In [4]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.99952016,  0.98935825,  0.41211849])

In [5]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 8.77496439, 2.82842712, 3.        ])

In [7]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029, -0.03097503, -0.14550003, -0.91113026])

In [8]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 4.34380542, 2.07944154, 2.19722458])

In [11]:
from numpy import pi

In [12]:
np.sin(pi/2)

1.0

In [13]:
np.cos(pi/4)

0.7071067811865476

In [14]:
pi

3.141592653589793

In [16]:
a = np.array([12.45,3.23,15.67,-9.17])
np.floor(a)

array([ 12.,   3.,  15., -10.])

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [18]:
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.reshape(arr,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [20]:
np.resize(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a = np.array([[1,2,3,4,5,6]])
a

array([[1, 2, 3, 4, 5, 6]])

In [46]:
a

array([[1, 2, 3, 4, 5, 6]])

In [48]:
c = lambda a,b:a+b
c(10,20)

30

In [49]:
c = lambda a,b:a*b
c(10,20)

200

In [60]:
D = lambda c :(9/5)*c +32
D(0)

32.0

In [61]:
w = lambda a,b :a**b
w(10,2)

100

In [62]:
np.fromfunction(lambda x,y :x+y,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [63]:
np.fromiter([1,2,3,4,5,6,],dtype = float)

array([1., 2., 3., 4., 5., 6.])

In [64]:
np.fromiter([1,2,3,4,5,6,],dtype = int)

array([1, 2, 3, 4, 5, 6])

In [68]:
np.fromstring("1 2 3 4 5 6 ",sep = " ",dtype = int)

array([1, 2, 3, 4, 5, 6])

In [75]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.eye(3,k = -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [79]:
s = np.array([[1,2,3],[4,5,6],[7,8,9,]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.diag(s, k = 0)

array([1, 5, 9])

In [90]:
np.tri(3,k = -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [96]:
np.tril(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.triu(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.diagflat([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])